carla:
  host: localhost
  port: 2000
  timeout: 10.0
  synchronous: true
  fixed_delta_seconds: 0.05
  weather: ClearSunset

camera:
  width: 1280
  height: 720
  fov: 70
  z: 60.0
  pitch_min: -90.0
  pitch_max: -70.0

display:
  enable: false

run:
  duration: 15
  cam_index: 45

traffic:
  vehicles: 70
  walkers: 10

processing:
  process_interval: 2
  enable_static_detection: true

export:
  enable: true
  export_interval: 4
  export_start_frame: 30
  export_end_percent: 0.95
  spawn_change_interval: 20
  weather_change_interval: 20
  max_exports: 200

